# Site settings
title: andrewwnewhouse.com
version: 3.0.3
excerpt_separator: <!--more-->

baseurl: ""

# Build settings
permalink: "/projects/:title/"
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - scripts

# Markdown settings
markdown: kramdown
kramdown:
  auto_ids:       true
  auto_id_stripping:    true

# HTML Compression settings
compress_html:
  clippings: [ ]
  blanklines: false
  profile: false
